### ISSUE TITLE
Map of bus stops that are connected to train stations

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#1]
As part of checking bus\train connectivity for 15 minutes, we want to understand what parts of the country are easily accessible from train stations.

The idea is 
1.  find bus stops that are near train stations 
2.  find all routes that stop in those stops, and see which other stops their reach

I  have initial results for this created with code in [my old repository](https://github.com/daphshez/kavrazif). There is a [map of of bus stops near train stations](http://www.arcgis.com/home/item.html?id=339635c669e646868424063677a60e94).  And there is [a map of stops from which can reach train stations ](http://www.arcgis.com/home/item.html?id=4eb7fc3074244295b7d4a6bf82c0da7d).

I am working now on:

1. Moving all the relevant code to this repository
2. Fixing some possible bugs 

Next tasks:

15 minutes have asked for the following features

1. Color code the distance from the station (e.g. use saturation)
2. Control over the parameters of drawing the map (e.g. the current map only shows stops up to 30 minutes from the station)
3.  Include all train stations (e..g in separate layers) . The current map doesn't contain the 10 most well served stations (mostly Tel-Aviv & Haifa).

Achieving all this seems to me to require a dynamic map (e.g. Google maps with some kind of backend). Will be happy for ideas about how best to do it (or help in doing it...)

**Comment by yaron1000** [comment]
hi think that  tasks 1, can been done
if you add new column distance from the station  to the table  its should be easy to set Color code 
2,3 can been done with arcgis online(not with a good user interface-many layer)
I guess  that with a Paid Version ArcGIS Online all of this task can been done(i only use arcgis desktop)

**Comment by daphshez** [comment]
@yaron1000 
Sorry I wasn't very specific on why I thought I wanted to move over from ArcGID Online.

The main reason is the number of features. I think there are about ~15-20K bus stops connected to train stations. AGOL actually complains when you try to import more than 1000 features. The current map includes about 3000 stops and it works. I guess I can try to generate a map with all the stops and see how it works...

The second reason is that I think that the number of features will create a visual clutter. So you would want to be able to turn stuff on and off  (e.g. stops that belong to different stations). This would require using several layers. And then importing manually several layers and configuring the colours every time there's a change is going to be a lot of work...

**Comment by daphshez** [comment]
There's a new version of the train station access map here:

http://www.arcgis.com/home/item.html?id=4eb7fc3074244295b7d4a6bf82c0da7d

The code for generating it is currently checked in under the kavrazif branch. 

I think this basically solves the requests from 15minutes for now, so I am marking this issue as closed.

**Comment by daphshez** [comment]
For future reference,[ the data files for the map layers are here](https://github.com/daphshez/openbus_data/tree/master/train_access_map_300m)
