### ISSUE TITLE
Add custom day cutoff capabilities to gtfs_stats

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#103]
As specified in this `partridge` issue https://github.com/remix/partridge/issues/37.

Add `day_cutoff` parameter (`HH:MM:SS`) to the config of gtfs_stats (default to midnight). This will cause relevant stats to be calculated using a day that starts and ends accordingly (currently days are based on calendar days, midnight to midnight)

This change will effect forward_fill too, and so make sure to make the proper changes and test this too (since this will use two calendar dates for every `day_cutff` that is different than midnight)

**Comment by adiwaz** [comment]
I implemented a function in gtfs_stats.py: compute_route_stats_time_cutoff.
Can be found in the branch here:
https://github.com/adiwaz/open-bus/blob/custom_day_cutoff/gtfs/gtfs_utils/gtfs_utils/gtfs_stats.py

We are currently waiting to build basic tests, and then will merge this one.

**Comment by adiwaz** [comment]
Update: 
We are currently updating our issues list, and I am no longer assigned to this issue.
The implementation I provided is present in a [separate branch](https://github.com/adiwaz/open-bus/blob/custom_day_cutoff/gtfs/gtfs_utils/gtfs_utils/gtfs_stats.py). Whoever finds it interesting is welcome to dive into the GTFS_stats code and integrate my/new solution to the day-is-currently-changing-at-midnight problem.

**Comment by OrBin** [comment]
Closing the issue, since it's not so necessary, and not worth our focus and work.
