### ISSUE TITLE
Check bus service boosting because of train works 

### ISSUE THREAD

**Issue by adiwaz** [hasadna/open-bus#110]
Tasks:
-------
* Compare two GTFS files (one old one new) to see whether the service change promises were actually kept.
* Publish results as a clear Jupyter notebook (to be published as a blog post).

Link:
------
https://www.rail.co.il/pages/updates/hismul-update.aspx

Details:
--------
The changes will begin on the night between Saturday 11.8.18 and Sunday 12.8.18 (00:01) and end on the night between 16.8.18 and Friday 17.8 (00:01).

The following bus lines should be boosted during the dates 12-16/8/18: 
412: Beit Shemesh-Tel Aviv
111: Modi'in-Tel Aviv
980: Haifa - Tel-Aviv Svidor (between the hours of 06:00 to 09:00 and between 15:00 and 19:00)
460/461: Lod-Tel Aviv
701: Hadera - Tel Aviv (between 06:00 and 09:00 and between 15:00 and 19:00)
605: Netanya - Tel Aviv

See #77 #76 #75 #73 #80

**Comment by cjer** [comment]
analysis code is here: https://github.com/cjer/open-bus-explore/blob/master/openbus_18_haifa_tlv_train_hishmul_boosts.ipynb

also wrote a facebook post about it.
this and all the other accountability analyses should be uploaded to our blog  (when it will be up) with a unique tag.

**Comment by cjer** [comment]
closing
