### ISSUE TITLE
Create jenkins task for nightly gtfs_stats

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#124]
Runs on the last day that has passed, creates trip_stats and route_stats files.
Uploads the results to Digital Ocean S3.
Run on new Digital Ocean server.

**Comment by OrBin** [comment]
@AvivSela, PR #205 changes the minimal Python version from 3.6 to 3.7. May it cause any problem with Jenkins?

**Comment by evyatark** [comment]
סדס€2
