### ISSUE TITLE
Upload siri logs to Digitalocean s3

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#130]
1. I uploaded the siri information from 01/09/18 to 01/11/18 to our s3 bucket in Digitalocean (example of file key: siri_logs/2018/10/15/siri_rt_data.2018-10-15.5.log.gz).
2. @cjer could you please approve #129 ?
3. @evyatark could you please call `open-bus/gtfs/retriever/s3_wrapper.py`
 and upload siri information daily? I can show you how i did it on Monday.

**Comment by cjer** [comment]
> @cjer could you please approve #129 ?
approved, uploaded entire gtfs_stats folder (in pickled gzip pandas dataframe format for now)

**Comment by AvivSela** [comment]
Solved in #145
