### ISSUE TITLE
Create report from Siri data per bus line across time

### ISSUE THREAD

**Issue by adiwaz** [hasadna/open-bus#135]
**Delve into Siri real-time data in the context of a specific bus line.**

**Goals:**
1. Detect problems with our Siri retrieval protocol
2. Understand and characterize the levels of noise in the GPS data
3. Gain a basic understanding of the data to develop anomaly detection models
4. Provide organized and useful information for the public

**Analysis details:**
1. Actual driven route - compare between trips, compare to the GTFS route shape. Detect deviations from planned route.
2. Detect unexecuted trips - can we distinguish between technical Siri problems and really unexecuted trips?
3. Trips duration - characterize the differences between trips in different times of day, compare to planned times.

**General plan:** Work on Siri data of a few specific lines from Oct-Nov 2018, and create generic code to generate similar reports on every line, given it's Siri logs data.

**Comment by AvivSela** [comment]
As we talked yesterday, the expected results of this issue will be 3 visualizations that we could include in a report.

**Comment by adiwaz** [comment]
**Issue is being closed and split into small tasks**
We are currently updating our issues and whole workout plans to have more focused and specific issues. This issue is actually a major goal of the Open Bus team: **combine real time bus data (SIRI) with planned routes and schedules to provide statistics about actual trips**. Therefore, we close this issue, and split it to smaller tasks. More details below.

==============================================
**More details:**
Working on this issue in the past months helped us to dive deeper into SIRI data and discover many basic issues we should deal with before we can confidently detect anomalies in bus trips data.
In particular, we should explicitly determine which SIRI fields can uniquely define a single trip (See issue #174 ). Then, we should create features per trip, such as: 
* Is this a full trip?  
* Do we trust the route number reported for this trip? Can we assign a more reliable route number?
* Is there a deviation from the planned route?
* Departure time (from first stop)
* Arrival time to intermediate/final stops
I suggest that the values of every such feature will be stored as a column in a table containing one row per trip ID. This way we can use more and more sophisticated logics to analyze the raw bus trips data, and then use this table to extract the desired report per bus line.
Good luck :)
