### ISSUE TITLE
App/web page for users to report about bus arrival

### ISSUE THREAD

**Issue by adiwaz** [hasadna/open-bus#139]
**Create a user friendly service on which people can report on arrival/not-arrival of buses.**

The goal is to tag our real-time bus data (Siri) with crowd information.
The collected data should be structured (and not free input), so it will be easy to parse and analyze.
The line and stops data should be taken from GTFS schedules, and preferably use the user's GPS signal to help her/him find the closest stop.

The data we want to collect:
1. Date of the reported event
2. Time of the reported event (Or option for a time interval)
3. Line number 
4. Stop (in which the user was present during the reported event)
5. Scheduled time of bus in this stop
6. Event, choose from: "Bus did not arrive", "Bus arrived and I boarded", "Bus passed but didn't stop".

You are welcome to suggest your ideas, and discuss implementation details.

**Comment by open-bus-israel** [comment]
I would use Open Data Kit - https://docs.opendatakit.org/getting-started -
I played with it and even created a form that one can use to mimic what 15
minutes gives as their complaint form on their website and app. I attached
the local copy of output form that it let me save on the computer.

I was able to create the form on their build site (build.opendatakit.org),
download it using ODK Collect on my android phone, fill the form, send it
to the sandbox aggregate server, and view/export the single line of data I
created as a CSV file that I downloaded to my local machine. I was also
able to download the exported form to my local machine, a Linux box using
Ubuntu 18.04.

Obviously, this is a work in progress (the form is incomplete and probably
has a mix of English and Hebrew thrown in), but if I, a non-programmer
amateur computer user can manage it, the impressive team of professionals
that is creating all the OpenBus bells and whistles, can implement
something that will scan an aggregate server and compile the data from the
CSV format used by the aggregate server, and put it into a complain
database.

If you take this road - I could use some help on projects collecting
surveys (including coordinates) that have to do with my public health
studies on travel medicine - which will aid public health of Israeli
tourists and backpackers - but that's outside the scope of OpenBus.

Cheers,

Z.

**Comment by open-bus-israel** [comment]
PS the form is text, open it with your favorite text editor. I use gedit or
nano from the command line.

**Comment by zvigrauer** [comment]
When you add a question on the form one of the options is Location, which
can be set to point, path or shape with a style of GPS (the phone's), show
map or manual entry. I only used point and phone GPS, so can't comment on
the other styles.

**Comment by TomerPacific** [comment]
@adiwaz , @AvivSela ,
following our meeting on Monday for the CivicHack, I am taking this issue.

I will try to create a simple application using [Flutter](https://flutter.dev/), so it can be compatible for both Android and iOS.

**Comment by ronlik26** [comment]
@TomerPacific  are you still working on this issue?

**Comment by TomerPacific** [comment]
@ronlik26 ,
besides the work I have during the hackathon, I have not invested more time into this project. There is a need to create backend endpoints from which the data needs to be retrieved (bus stations according to location, where to send the form data to).  Do you know of any plan to do this or to bring this project to life?
