### ISSUE TITLE
Delete temp files of the GTFS reader of SIRI client  

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#143]
Currently the GTFS reader of SIRI client download the zip and extract it into temp files bun never delete them. After the GTFS reader finish to download and parse the GTFS information the files should be deleted.

**Comment by eldadru** [comment]
Starting to work on this issue

**Comment by eldadru** [comment]
Status Update: made significant progress today, the code is ready, performing tests to understand if it's working properly

**Comment by eldadru** [comment]
PR: #158

**Comment by eldadru** [comment]
Merged to master
