### ISSUE TITLE
Present GTFS & SIRI data of multiple trips as Leaflet Widget

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#151]
Build a web page that shows rides on a leaflet map 
- The information that should be presented as layers on the map: 
  a. shape of planned route.
  b. bus stations.
  c. other lines that stop at the station.
  d. records of real-time location of the bus.
  e trip information 
- example of data: TBD
- please include the example data as a stub in your code so that in the future we could use DB to get the information
- API documentation could be found here: http://142.93.111.211:8081
- REST Server could be found here: http://142.93.111.211:3000/trips/1

**Comment by evyatark** [comment]
I have worked on this issue during the March 2019 Hackathon, and I wish to reach a presentable level. You are invited to join - there is a lot of work for everyone!
