### ISSUE TITLE
Refactor GTFS Stats package/script

### ISSUE THREAD

**Issue by OrBin** [hasadna/open-bus#161]
gtfs_utils.py and gtfs_stats.py are long, messy files. They should be split.

Also, we should think about making it more modular, so the package will be used for other means in addition to generate trip_stats and route_stats.

**Comment by cjer** [comment]
what I have in mind:
1. Design with tests in mind (against actual files, including older versions)
1. Merge duplicate code/functionality between gtfs_utils/gtfs_utils.py and gtfs/retriever.
1. Decouple functionalities in gtfs_utils/* (what I can think of at the moment): 
   1. download (FTP/S3)
   1. GTFS processing (mostly take a GTFS file, read, filter and transform it to tidy DataFrames)
   1. external files processing (TripIdToDate, Tariff etc.)
   1. merges between files (merge logic between GTFS and all other files)
   1. statistical summary GTFS, with optional merged files (this outputs route_stats and trip_stats, in the future there will be more: stop_stats, shape_stats...)
   1. output (standard formats: pickle, csv, json, in the future maybe)
   1. main run logic - on a single gtfs file, against a local folder with all/some of the files, historical run against our s3 archive, with optional local archive, output to the selected format and location
   1. handling older versions of older gtfs and external files differently (when MoT's changes versions of the standards, we need to be able to keep running on historical versions properly) 
   1. configuration
1. Put these into separate modules

**Comment by OrBin** [comment]
@cjer, when you talk about testing against older versions of files, what does it mean? Did MOT's files change? When and why?

**Comment by OrBin** [comment]
@cjer, Can I remove `batch_stats()` from gtfs_stats.py? It seems like nothing uses this function.

**Comment by cjer** [comment]
Older versions - yes, they make changes sometimes. I remember at least one big change in how they set the zones for stops in Tariff.zip last year.
`batch_stats` - yes, it's obsolete.

**Comment by OrBin** [comment]
Note: in 9a6ac1c, I've shortened the aggregation inside compute_trip_stats_partridge, and **changed some column names** (it was necessary for making the code shorter and more readable):
* start_time -> start_departure_time
* end_time -> end_departure_time
* start_zone -> start_zone_name
* end_zone -> end_zone_name

**Comment by OrBin** [comment]
> Note: in [9a6ac1c](https://github.com/hasadna/open-bus/commit/9a6ac1c0d707758a9f8b099b97fc3cb575282d69), I've shortened the aggregation inside compute_trip_stats_partridge, and **changed some column names** (it was necessary for making the code shorter and more readable):
> 
> * start_time -> start_departure_time
> * end_time -> end_departure_time
> * start_zone -> start_zone_name
> * end_zone -> end_zone_name

I should add renaming these column names for backwards compatibility.

**Comment by OrBin** [comment]
Created #188, #189, #190 and #192 And put them into milestone [GTFS stats refactor](https://github.com/hasadna/open-bus/milestone/4)

**Comment by OrBin** [comment]
All the subtasks are done, so I'm closing this "parent" issue.
