### ISSUE TITLE
bus2train: enhance the trains vs bus arrivals spreadsheet

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#17]
A few months ago I prepared [this spreadsheet](https://docs.google.com/spreadsheets/d/1M6HrPnz1H18Tyd59oOxa5Nvo-hd5PzFy4rkWU76mmTQ/edit#gid=1615610302) for 15 minutes. 

It gives for each 1 hour window, the number of train arrivals to the station, and the number of bus arrivals. The ratio gives a crude estimation of how good the train station is served by buses.

There are a few updates that this file needs:
1) The table is based on straight line distance between bus stops and stations. Now that we have walking distance data ([available in the db](http://data.obudget.org/queries/761)), we should re-compute using only buses with reasonable (up to 300m) walking distance.

2) We were asked to take the "importance" (number of passengers) in each station into account. We have [data on number of passengers here](https://github.com/daphshez/openbus_data/tree/master/train_station_passengers).
I think the first thing to do is just to export the average number of passengers as an extra sheet in the Excel output.

The code I used to create the file initially is here, but I think it would make more sense to re-write it from scratch using the GTFS the DB.

**Comment by MYank0** [comment]
I updated the spreadsheet. You can find it [here](https://drive.google.com/open?id=1-v1UvaJxkeD46N6sKis41L15fPonMOzuBvnlPHYdGrk).

What's new?
1. Re-computed distance between bus stops and stations using walking distance table. (up to 300m)
2. Added data for weekends.

You can see the original bus data [here ](https://drive.google.com/open?id=0B9FEqRIWfmxLS0hzdXBZQS1FMUU)and train data [here](https://drive.google.com/open?id=0B9FEqRIWfmxLSGIwSmFqOVZzTnM). (The full list of all train and bus hours and the SQL query)

Please note the following stations don't have a bus stop closer than 300m according to google maps:
בני ברק,נתבג,ירושלים מלחה.
Would we like to check separately these stations with greater distance?

The following stations are new so also don't have data:
עפולה, בית שאן, כפר ברוך, כפר יהושע, נתניה קריית ספיר

About the "importance" (number of passengers) in each station:
Tapuz forum has this [table ](http://img2.timg.co.il/forums/2/e15e9291-a053-4f6d-9775-a33c12912956.xlsx). Maybe we can use it to rank the station? I'm not sure if it is raw data from MOT or conclusions from the [table ](https://github.com/daphshez/openbus_data/blob/master/train_station_passengers/passenger%20by%20line%202016-01-04.xlsx) per lines.

**Comment by daphshez** [comment]
@MYank0 

Looks good! Please mail it to Gil Yaacov as well (when you feel it's ready anyway). 

1. Is there code you can commit that was used to create this? It would be useful to be able to recreate it.

2. Re:בני ברק, נתבג, מלחה - I think it's probably because of problems with the Google Maps routing rather than not actually having stations there. Maybe the graphhopper distance will be more appropriate? I think in most cases taking the minimum between the two options is be a better estimation.

3. Re:רכבת העמק, we can generate a map of stops around the stations (Google Fusion Table is the easiest way), and then look for someone who has been there and could estimate distance manually. Maybe Gil can help with that to. Will you be able to create the map? 

4. I loaded the data from Tapuz into a database table `train_passenger_counts`. See the [db_tables](https://github.com/hasadna/open-bus/blob/master/doc/db_tables.md) readme for information about the content.

**Comment by daphshez** [comment]
This has mainly be dealt with as part of bus2train.
