### ISSUE TITLE
כתיבת הסברים (באנגלית ובעברית)י

### ISSUE THREAD

**Issue by evyatark** [hasadna/open-bus#175]
כתיבת הסברים (באנגלית ובעברית) על שיטות עבודה מוצעות, החל מאפריל 2019, בעקבות הפגישה ב15 באפריל

product: [this page](https://github.com/hasadna/open-bus/wiki/%D7%A2%D7%91%D7%95%D7%93%D7%94-%D7%9C%D7%A4%D7%99-%D7%9E%D7%A9%D7%99%D7%9E%D7%95%D7%AA)!

and [this one](https://github.com/hasadna/open-bus/edit/siri-doc/siri/) also...

**Comment by OrBin** [comment]
Is Hebrew really needed? I think that maintaining documentation in two languages will make one (if not both) of them become out-of-date at some point.

**Comment by evyatark** [comment]
I truly hope that Hebrew is NOT needed. But it means that everybody should be prepared to write in English. And if someone is not fluent in English, he/she might not participate.

**Comment by OrBin** [comment]
You are right, but I believe it's an elementary requirement. Am I wrong?

**Comment by evyatark** [comment]
You are correct. But we should check if all current team members feel ok to write in English

**Comment by evyatark** [comment]
I added a strong recommendation to NOT use Hebrew.

**Comment by cjer** [comment]
Two comments - 
1. I think this content should appear in a `CONTRIBUTING.md` file . Github also has built-in features for directing people to read and comply to contribution guidelines ([see here](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors))
1. I opened an issue for organizing our issues #185  (we're entering the matrix here I know). The issue labels should be simple and helpful to our task management, so I would love your input on that. After we agree on labels we should update the contribution guidelines content too.

About English - I wish we could do all this in Hebrew. If RTL is the main concern, there are some solutions (https://github.com/dear-github/dear-github/issues/147#issuecomment-346978279). It does require minor getting used to.  If English only content will make our disscussions less efficient and open, I think we should think of a solution that will work well for Hebrew. 

<div dir="RTL">קצת מצחיק שכתבתי את כל זה בעברית. קיצר, יש פתרונות ל-RTL. הטקסט הזה הוא דוגמא. ואם זו הבעיה המרכזית, ואנגלית תגרום לדיונים להיות פחות זורמים אני חושב שכדאי לעבוד על להשריש את השימוש בהם. מאילו סיבות אתם חושבים שכדאי להתנהל פה באנגלית בלבד?</div>

**Comment by evyatark** [comment]
גם הדאגה שלי היא שדיונים לא יזרמו אם נעבור לאנגלית בלבד.
אצל מפתחי תוכנה בדרך כלל עובדים רק באנגלית. מכל מיני סיבות. בעיקר זה שכל המונחים המקצועיים הם באנגלית, אז אם אתה כותב בעברית אתה צריך לעבור בין עברית ואנגלית בערך כל משפט. שזה מציק מאוד. וגם ברוב האדיטורים (הנה דוגמה למונח שצריך להיות באנגלית) אין ממש תמיכה בכתיבה ועריכה מימין לשמאל.

**Comment by cjer** [comment]
<div dir=rtl>
הבעיה המרכזית -"אנגלית בלבד" בעיני היא שאנחנו רוצים שה-Issues פה יהיו גם תחליף לפורום, ולא רק מקום ל-Features ו-Bug-Requests מוגמרים.  אני חושב שבטווח הארוך זה יגביל מאוד את אופי או את משתתפי הדיונים כאן אם הכל יהיה באנגלית. אשמח לעוד דעות @AvivSela  @adiwaz  @ronlik26 @eldadru 
</div>

**Comment by cjer** [comment]
<div dir=rtl>
או שכדאי למצוא מקום אחר לקיים בו דיונים ולשאול שאלות, שיהיה נוח לתקשר בו בעברית. (והוא יוכל גם לתפקד יותר כמו פורום, למשל שנושאים עם תגובות חדשות יקפצו למעלה). 
</div>

**Comment by evyatark** [comment]
<div dir=rtl>
ידע לא צריך להיקרא מתוך דיונים. אם במהלך הדיון יש משהו שהוא "ידע" אז כדאי מאוד לכתוב אותו ב WIKI

דן - האם מוסכם שעמודי ה WIKI שמרכזים את הידע שלנו כן יהיו באנגלית בלבד?
</div>

**Comment by cjer** [comment]
<div dir=rtl>
זה נכון לגבי דברים שמזהים מראש שהם חשובים מספיק. ברור למשל שלא נשלח משתמשים או מתנדבים חדשים לנבור בדיונים כדי ללמוד דברים בסיסיים. ה-WIKI צריך להיות מקום לדברים האלה - מקום ברור ומתומצת שמרכז בצורה טובה את הדברים הקיימים והמוסכמים. אבל תמיד יש עוד ידע בשאלות-תשובות ודיונים שמוצאים בדיעבד שהוא חשוב.

עמודי WIKI נשמע לי בסדר גמור שיהיו באנגלית (אפשר גם ליצור בעתיד גרסאות מקבילות מתורגמות אם נראה לזה צורך). הבעיה שלי היא בעיקר עם דיונים ושאלות-תשובות.
</div>

**Comment by OrBin** [comment]
עוד נקודה - האם אנחנו צריכים להתחשב באנשים שלא דוברים עברית?
אלה יכולים להיות אנשים שגרים בישראל, או אפילו אנשים ממדינות אחרות שיכולים להתעניין בפרויקט. בסה"כ נראה לי שרוב מה שאנחנו עושים לא ייחודי לישראל...

**Comment by AvivSela** [comment]
<div dir=rtl>
אפשר גם לשלב - את הדיונים #discussion לא נגביל להיות בשפה מסויימת
ואת שאר הדברים שאמורים להיות סגורים ומוגדרים יותר נעשה באנגלית

לגבי הסברים בוויקי הייתי כותב באנגלית ומתרגם את אלו שאמורים לפנות לקהל שחדש בפרוייקט ודובר עברית
</div>

**Comment by OrBin** [comment]
שוב, הבעיה בלתרגם היא שתמצא את עצמך עם תוכן לא מעודכן באחת מהשפות (אם לא בשתיהן...)

**Comment by AvivSela** [comment]
זה לא שכתיבה בשפה יחידה יהפוך את זה למעודכן...
אבל אני מסכים איתך.
מה שכן אני חושב שיש טעם לכתוב בעברית כאשר יש קהל יעד מוגדר אליו כותבים. 

אני חושב למשל שכן כדאי שיהיה בעברית טקסט שמכיל את מה שנאמר בעל פה בכינוסי המתעניינים של הסדנה ובעת כניסת מתנדבים חדשים לפרויקט

**Comment by adiwaz** [comment]
Closing this issue. We have other issues opened for documentation, and future tasks.
