### ISSUE TITLE
Add "planned_start_time" date to SIRI data

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#182]
For calculating trip index in SIRI data we need to add "planned_start_time" date as a new column in SIRI data.

**Comment by evyatark** [comment]
It is a simple change in the Java code of siri-retriever. I can do it tomorrow.

**Comment by EyalBerger** [comment]
Great! after the change, could we download it from Splunk for new data only or also for historical data?

**Comment by AvivSela** [comment]
> Great! after the change, could we download it from Splunk for new data only or also for historical data?

For new data only

**Comment by cjer** [comment]
Hey, we have to make sure to update our SIRI processing code before/shortly-after we go live with this change. 
I was thinking of going over all of the changes/additions we want for SIRI log and add them all at once maybe (we can call it a new siri log version, I have opened  a new issue #183 to discuss all of the requested features for the new SIRI log version). Have a look at what I said about the `DataFrameRef` field in the SIRI response. I think it might help us with this issue.

**Comment by EyalBerger** [comment]
Thanks. 
As for  `DataFrameRef ` field, I assume that we will need to export it from SIRI raw data, along with the other date fields you have mentioned in #183, and then figure out what is the best one to use for trip indexing.

**Comment by evyatark** [comment]
what is called here "planned_start_time" is actually called (in Siri terms) OriginAimedDepartureTime.
It is done as part of issue #183

**Comment by EyalBerger** [comment]
"planned_start_date" field added to SIRI. 
I will update the *Getting started* notebook of SplunkUtills, Then close this issue.

**Comment by cjer** [comment]
@EyalBerger Anything we're missing for closing this issue?

**Comment by EyalBerger** [comment]
I still need to do this small update in *Getting started notebook of SplunkUtills*.

**Comment by cjer** [comment]
@EyalBerger 
Can we close this now?

**Comment by EyalBerger** [comment]
Yes.
As part of the bus-only lane analyze I made some improvements in SplunkUtils. When it's will be ready for upload, I'will also update the Getting started notebook, including this point.
