### ISSUE TITLE
SIRI log v2 features - in siriRetriever Java app read more data from the arriving XML response

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#183]
These are the changes I know of, after we reach an agreement, separate issues should be opened for every change/addition (A separate issue for documenting SIRI log v1 #184 , and once we agree here one should be opened for SIRI log v2 documentation):
1. output full timestamp for OriginAimedDepartureTime (#182), as it appears in the response: 2019-04-01T20:50:00.000+03:00
1. same for RecordedAtTime
1. same for ExpectedArrivalTime
1. also concerning #182, I noticed the SIRI response contains a field named DataFrameRef, which holds a date (e,g, `2019-04-01`). It is not documented in MOT pdfs, but in [SIRI documentation](http://laidig.github.io/siri-20-java/doc/schemas/siri_journey_support-v2_0_xsd/elements/DataFrameRef.html) I see it reads: "identifier of data frame within particpant service. Used to ensure that the Reference to a DATED VEHICLE JOURNEY is unique with the data horizon of the service". As I understand it, THIS is the field that should hold the information we're looking for in this issue, combined with trip_id (in SIRI named  DatedVehicleJourneyRef).
1. consider adding the stop_code (StopPointRef in SIRI response), so we know for sure what is the last stop for the SIRI record, without having match it with GTFS 
1. @evyatark , I remember you said something about getting a field in the response that contains information about whether the bus is at the stop or not. I did not see it in the response examples you sent me. 
1. EDITED: add log version to file name

**Comment by evyatark** [comment]
regarding StopPointRef in SIRI response (point number 5 in this issue),
it seems to me that since we always query the last stop of the route, we already have that value in the "DestinationRef" item. But if in the future we will query stops along the route (that are not the last stop), then the values will be different (DestinationRef is always the last stop, StopPointRef is the stop for which we queried). So I will add StopPointRef (for future use)

**Comment by evyatark** [comment]
commit [660bf80](https://github.com/hasadna/open-bus/commit/660bf805b0f14ffca1a232e4ca1ab2b8493a4ad6) completes all requirements of this issue. I will add some tests, and then merge to master and deploy to PRODUCTION machine.

**Comment by cjer** [comment]
That's great! Can you send a example log? I need to make the necessary updates in the pre-processing and in the splunk code (@EyalBerger your new SplunkUtils too I guess) ,preferably before you go to PRODUCTION.

**Comment by EyalBerger** [comment]
Sounds great!
As for **SplunkUtills** , I don't think any change is needed when adding new fields to SIRI, but I would make a small change in my **Getting Started** notebook after the changes will go to production. Please update here when it's the the right time for that.

**Comment by evyatark** [comment]
Completed implementation, and deployed.
As of 2019-06-11 all Siri results logs are in the new format (v2)
(sent merge request)
