### ISSUE TITLE
Update gtfs_stats documentation

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#186]
**Output**: A wiki page with all of the points below

- [x] an executive summary of `gtfs_stats` (goals and use cases)
- [x] field documentation for `trip_stats` and `route_stats` with clear explanations for outside users.  Not internal definitions as they are in the code now. Include examples and field types.
- [x] the different ways to run `gtfs_stats` with examples.
- [x] output file formats
- [x] how they appear in splunk

----
- [x] Host the new documentation in ReadTheDocs

**Comment by OrBin** [comment]
We've just talked about this issue, so a few notes:
1. A markdown file may be preferred over wiki, since it is located in the repository and will be up-to-date with the code.
1. Auto-generating docs from the docstrings in the code would be even better. I should check out how easy it is to do it with Sphinx. If we find it a good solution, we can host it in readthedocs.

**Comment by OrBin** [comment]
> **Output**: A wiki page with all of the points below
> 
> * [ ]  an executive summary of `gtfs_stats` (goals and use cases)
> * [x]  field documentation for `trip_stats` and `route_stats` with clear explanations for outside users.  Not internal definitions as they are in the code now. Include examples and field types.
> * [ ]  the different ways to run `gtfs_stats` with examples.
> * [ ]  output file formats
> * [ ]  how they appear in splunk

* Do we have more than one way to run `gtfs_stats`?
* Do we have more than one output file format?
@cjer

**Comment by cjer** [comment]
> Do we have more than one way to run gtfs_stats?

What I had in mind was more like different configs that can be used for example: a) running it on a single date (i.e. latest gtfs) b) running it on a long period c) running with forward fill

> Do we have more than one output file format?

You're right. Right now `gtfs_stats` only outputs pickles. I run a local script to convert it to csv. This should be added to gtfs_stats (and drop the pickle thing altogether).

> I'm really not sure how they appear in splunk. Can you help me with that?

Sure - I will add it where necessary

**Comment by OrBin** [comment]
> can

**Comment by OrBin** [comment]
> > Do we have more than one way to run gtfs_stats?
> 
> What I had in mind was more like different configs that can be used for example: a) running it on a single date (i.e. latest gtfs) b) running it on a long period c) running with forward fill

There are determined by `bucket_valid_file_name_regexp` and `forward_fill` in the configuration file, am I right?

> > I'm really not sure how they appear in splunk. Can you help me with that?
> 
> Sure - I will add it where necessary

OK. I will make a suitable location for this information and leave a placeholder for you. Alternatively, you can write about it and send to me/post it here.

**Comment by OrBin** [comment]
> > > Do we have more than one way to run gtfs_stats?
> > 
> > 
> > What I had in mind was more like different configs that can be used for example: a) running it on a single date (i.e. latest gtfs) b) running it on a long period c) running with forward fill
> 
> There are determined by `bucket_valid_file_name_regexp` and `forward_fill` in the configuration file, am I right?
> 
> > > I'm really not sure how they appear in splunk. Can you help me with that?
> > 
> > 
> > Sure - I will add it where necessary
> 
> OK. I will make a suitable place for this information and leave a placeholder for you. Alternatively, you can write about it and send to me/post it here.

I've just submitted PR #242, which solves both of these, but does not yet close this issue.

**Comment by OrBin** [comment]
The docs are at https://open-bus-gtfs-utils.readthedocs.io/en/latest/
