### ISSUE TITLE
Retrieve Hackathon projects from the participants  

### ISSUE THREAD

**Issue by ronlik26** [hasadna/open-bus#187]
We need to contact the people who participated in one of our challenges and ask them for their project

**Comment by cjer** [comment]
- [Matching of Recorded Bus Trips to Planned Routes](https://github.com/ido90/Transportation),  Ido Greenberg and Oded Shimon
- [bus-bottlenecks](https://github.com/dincaz2/bus-bottlenecks), Shaked Kaufman et. al. 
- [Route Plan Angel & Bottleneck Analysis](https://github.com/amirlb/civilhack-2019), Barak Yossipovch, Amir Livne Bar-On, Dalya Gartzman, Noa Raindel
