### ISSUE TITLE
Sample data does not include 'shape_dist_traveled' column

### ISSUE THREAD

**Issue by bennyz** [hasadna/open-bus#19]
Because of the missing column, the `insert_gtfs.sql` script fails with the error:
`ERROR:  missing data for column "shape_dist_traveled"
CONTEXT:  COPY stop_times, line 2: "20132304_260516,09:11:35,09:11:35,1321,44,0,0"
`

This is can be fixed by using a newer data set which includes the missing column.
@avielb and I can submit a PR with a new sample if needed.

**Comment by daphshez** [comment]
Please do. Maybe also submit the code used for creating the sample, for the next time fields are changes and a new sample is needed?

**Comment by Bennyz** [comment]
We will submit a script as well. We plan on taking the first 1000 lines or so from each file, will that do? Or are there some other requirements for creating the sample data?

**Comment by daphshez** [comment]
Unfortunately it's a bit more complicated than that. There are dependencies
between the tables. You wouldn't want to have say trips without the routes
they depend on.

What I would be good is to have the first 10 trips, and the related records
from routes, calendar, stop_times and shapes files. To keep things simple,
the original complete stops file can be kept (it's not huge,  ~30k
records).

There's a dependencies diagram is in doc folder.
