### ISSUE TITLE
Analyse train passenger count data: new dataset! never seen before! 

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#20]
We have received (sort of, see below) from Israel Railways data about the number of people starting and ending their journeys at each train station, for each date between April and October 2016, for each hour of the day.

We have asked for the data in order to understand which stations need better bus service, and when (this is for the bus2train project). However I think this is the first time this kind of data is made public, and there's probably more interesting stuff to do with it. 

The original file is here: https://drive.google.com/open?id=0B_MFjF7hDGLcRGVKaklvSERWUmM

And there's a CSV of the data here https://drive.google.com/file/d/0ByIrzj3OFMnIMGxWQk5RaFM5Yjg

Unfortunately there are a few problems with the data:
1) We received only data for ends of journey (number of people leaving the station), and not starts of journey
2) We are missing data of many of the stations (there's only partial information for Segula & Tel-Aviv Centre, and everything between them in alphabetical order is missing)

We have written to Israel railway to ask for fixed data. When we get it I'll put everything in our DB.

**Comment by MYank0** [comment]
1. Data uploaded to database under the table "train_passengers_per_hour". When we receive the new data we can quickly update it. I will commit the script that helps with the upload.
2. Re:dash SQL query to get average of passengers by day of the week is [here](http://data.obudget.org/queries/839/). 
3. I started making a spreadsheet of ratio between number of passengers arriving and bus leaving the station.
4. Something is odd about the column n_passengers - there are some rows that miss that info and some have real numbers. Can we ask Israel railway how comes some of the numbers are real and not integer?

**Comment by MYank0** [comment]
Hi!
We got new new and full data from Rakevet Israel!    :smile:
Raw csv can be found [here](https://drive.google.com/open?id=0B9FEqRIWfmxLMDl4VnBKcU1Qd0E) and data also uploaded to "train_passengers_per_hour" on Postgres.

**Comment by daphshez** [comment]
The original Excel files from Israel Railway, if someone is interested:

https://drive.google.com/drive/u/0/folders/0B9FEqRIWfmxLZllpdzlndVh2TVE
