### ISSUE TITLE
Add all_stop_name field to route_stats

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#224]
Add a field to route stats named `all_stop_name`. 
The field will contain `stop_name`s for all stops for ordered by stop time, separated by a semicolon `;` (as in `all_stop_code` and `all_stop_latlon`). Remove semicolons that are present in the original `stop_name` with a colon `:`.
Add it to the test assets.

**Comment by OrBin** [comment]
Closed in #282.
