### ISSUE TITLE
Adjust create_siri_csv_splunk.py to new SIRI log format

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#237]
- Execute: _python3 ./pipeline/create_siri_csv_splunk.py ./logs ./splunk_logs_ failed with the following:

> ./logs/siri_rt_data_v2.2019-06-11.18.log.gz
> list index out of range
> Traceback (most recent call last):
>   File "./pipeline/create_siri_csv_splunk.py", line 71, in <module>
>     main(FOLDER,out_folder)
>   File "./pipeline/create_siri_csv_splunk.py", line 67, in main
>     df.to_csv(out_path, compression='gzip', index=False)
> UnboundLocalError: local variable 'df' referenced before assignment

- It seems that an exception is thrown from there:
https://github.com/hasadna/open-bus/blob/94b5d82fdc918435b613deacc8260391df192aa1/pipeline/create_siri_csv_splunk.py#L21 

- example of new format siri log file could be found here:  https://gofile.io/?c=dEie0Q

- background:
@evyatark: 
"As of last night, Siri switched to producing results using an updated format. (issue #183)
some of the changes are (see issue #183 for more details):
all time fields now include also the date
added 2 fields
the file name is now siri_rt_data_v2.log

**Comment by cjer** [comment]
closed in #240
