### ISSUE TITLE
Add TripIdToDate info to GTFS Stats

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#239]
Add the trip ID as it is present in the relevant `TripIdToDate` file to GTFS stats (trip_stats and route_stats)

**Comment by TheFrok** [comment]
I think I might misunderstood this issue.
The intention was to add a new column with the with the trip id in the format it appears in the `TripIdToDate` (seems it contains just the first number, before the `_`)
Or to add more information from the `TripIdToDate` file?

@cjer

**Comment by cjer** [comment]
You got it right.  Just notice that it is not the same ID as the GTFS `trid_id`. GTFS `trip_id`s repeat themselves between weekdays (the ID will be the same Sunday, Monday, Tuesday etc... as long as the service is repeated). The IDs in `TripIdToDate` are unique and don't repeat between weekdays.  These IDs  are also the ones that (should) match SIRI records.

From MoT's documentation:
![image](https://user-images.githubusercontent.com/9987721/71633125-0a7e2600-2c1b-11ea-8a56-d85ff76d808a.png)
![image](https://user-images.githubusercontent.com/9987721/71633133-14a02480-2c1b-11ea-970b-7bf0cdb7a072.png)

**Comment by TheFrok** [comment]
Some rows are duplicated in every aspect except TripIdToDate.
For example:
>       route_id  OfficeLineId  Direction LineAlternative   FromDate     ToDate  trip_id_to_date  DayInWeek  departure_time
>       21974      458         31087          2               2 2018-12-11 2200-01-01         15147298          3         48600.0
>       21981      458         31087          2               2 2018-12-11 2200-01-01         15147305          3         48600.0
(from the TripIdToDate of 2019-03-07)

@cjer  what do you think we should do with that? Just insert both of them?

**Comment by cjer** [comment]
It looks like the `route_id` is different, doesn't it?

**Comment by cjer** [comment]
OK I think it is actually valid - two different trips of the same route that start on the same hour (its a school line).
We need to keep both of them. We're just left with the issue of what GTFS trip to join with. 
Maybe sort both by trip_id and then join these by their order?

**Comment by TheFrok** [comment]
So the lower `trip.trip_id` will get the lower `TripIdToDate.trip_id` and the higher one will get the higher one?
Seems fine to me

**Comment by TheFrok** [comment]
@cjer I continued what we did yesterday and found 4 `route_id`s that are duplicated in trips:
`['12032', '12607', '14819', '9447']`
trip_ids for `12607` for example `36469559_070319 , 36469564_070319` (These are for 09:00)
This is the only line from the `TripIdToDate`:
`12607,10982,1,#,01/02/2019 00:00:00,01/01/2200 00:00:00,36469563,5,09:00,`
(Again all the that is based on gtfs from 2019-03-07)

**P.S.** Do there a code that fixes date and time of departure time after 24:00?
