### ISSUE TITLE
Find trip id for SIRI arrival 

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#24]
We aggregate bus trips in real rime from the SIRI protocol. The results are in the siri_arrivals table. 
We also have data on planned trips in our GTFS tables. 

We want to link the data in siri_arrivals to the GTFS trips table, by adding a trip_id column to siri_arrivals. 

This should be possible based using the following data from siri_arrival:
* line_ref   (which should be GTFS route_id)
* day of week
* origin_aimed_departure_time 

There should be one and only one trip with the given route_id, that runs on the given day of week and departs from the first stop at the given aimed departure time. 

This task is to create a script\query that:
* adds a trip_id field to siri_arrivals
* fills it with the correct trip_id

If you only require sql to do it, add the query file to the /postgres folder. If you need to write Python code, put it under /siri. 

**Issues you may run into**
* We aren't sure how reliable the origin_aimed_departure_time departure time is. Does it actually contain sensible data?
* Our GTFS tables contain data from a single GTFS file (from 8/2/2016). GTFS is published nightly and may include changes in the planned schedule. It's possible that some of the siri_arrivals data, especially towards the end of the month, won't match the data in our GTFS tables. If you get low match data. 

**What's would you need to implement this?**
* SQL, maybe some Python. 
* Some understanding of GTFS, particularly the gtfs_trips, gtfs_calendar and gtfs_stop_times tables. [Get started by reading this](https://github.com/hasadna/open-bus/blob/master/doc/working_with_GTFS.md). As a starting point, this query returns trip ids and the start time for each trip, and also on which days it's running:

```
select route_id, trip_id, DEPARTURE_TIME, sunday, monday, tuesday, wednesday, thursday, friday, saturday
from gtfs_trips 
join gtfs_stop_times on gtfs_stop_times.trip_id = gtfs_trips.trip_id
join gtfs_calendar on gtfs_calendar.service_id = gtfs_trips.service_id
where route_id = 7020
and stop_sequence= 1
```

* Basic understanding of the siri_arrivals table (see #31)
* It's possible that this task can be implemented as an SQL query. You can use [our re:dash](http://data.obudget.org/) to play with queries against our database. 
* If you need to write a script, you will probably need a local development database to play with (#32)
* Clone the repository and use pull requests to submit your code.

**Comment by NadavLidor** [comment]
We produced a join query at: http://data.obudget.org/queries/1090/source

We see that only about 50% of SIRI entries are matched with a relevant GTFS trip_id.
From our study, we believe this is due to discrepancies between SIRI and GTFS departure times . 
For example, for route_id/line_ref '7020' on date 2016-12-28, there is a SIRI entry for departure time at 6:10 AM but GTFS has an entry for 6:12 AM, and so these cannot be joined.
To see this, here are two queries:
SIRI departure time for line 7020 on 2016-12-28: http://data.obudget.org/queries/1091/source
GTFS departure time for line 7020 on 2016-12-28: http://data.obudget.org/queries/1092/source

**Comment by hanan-cohen** [comment]
Found a bug in the example query [Issue 24: SIRI departure times for line 7020 on 2016-12-28](http://data.obudget.org/queries/1091/source)

On line 2 - HH24:**MM**:SS should be HH24:**MI**:SS

MM is Month, MI is Minutes

Forked it to [Copy of (#1091) Issue 24: SIRI departure times for line 7020 on 2016-12-28](http://data.obudget.org/queries/1101/source)

**Comment by hanan-cohen** [comment]
In gtfs_trips, start_date for line_ID 2070 (480) is 2016-12-31. Maybe it's not a good idea to test the query for 2016-12-28. I am testing my queries on 2017-01-11 (Wednesday).

**Comment by hanan-cohen** [comment]
There is an offset of 2 hours between the data in SIRI and the data in GTFS.
In SIRI, the time is recorded as 2017-01-02T04:15:00+00:00 and it should be 2017-01-02T04:15:00+**02:00**.

Matching the data for 2017-01-02, 89 lines, without the offset there are 46 matched lines, while with SIRI time+2 hours there are 88 matched lines.

Time zone and Daylights saving time should be considered when comparing the times between the two data sources.

See the attached Excel file.
[compare GTFS - SIRI 2017-01-02.xlsx](https://github.com/hasadna/open-bus/files/1063838/compare.GTFS.-.SIRI.2017-01-02.xlsx)

**Comment by MYank0** [comment]
Currently our [script ](https://github.com/hasadna/open-bus/blob/master/postgres/adding_trip_id_to_siri_from_gtfs.sql) only matches ~75% of the trips. Need to improve it and understand why some siri trips don't match the gtfs.
