### ISSUE TITLE
As a developer i wish that jenkins jobs (pipelines) will be part of the code

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#252]
Our Jenkins jobs executes our code. In order to keep the jobs and the code without compatibility issues (for example: script file name changed without updating the job) it will be better to include the jobs in the code. 

This will allow a developer that make change in the code also check the potential affect on the jobs and update them if needed. 

The jobs:
- [x] Convert to Code: GTFS_Download_And_Archive
- [x] Drop: (legacy) Upload_SIRI_Logs_To_S3
- [x] Create: SIRI_logs_ETL (replacing Upload_SIRI_Logs_To_S3)
- [x] Drop: Daily_SIRI_Upload
- [x] Create: check_for_new_SIRI_logs (replacing Daily_SIRI_Upload)

**Comment by AvivSela** [comment]
All pipeline files created in branch "jenkins-pipeline-jobs-as-code".
All active jobs in Jenkins retrieve the last pipeline file from git

i will keep testing it in local branch next week and then will merge it to master

**Comment by OrBin** [comment]
Closed in #257
