### ISSUE TITLE
Add route offset to siri_arrivals [depends on #29, #30]

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#26]
siri_arrivals table contains the GPS locations of buses. As a step towards estimating the buses arrival time to stops, we need to find the route offset of the bus at that point:

<img width="470" alt="route_offset new" src="https://cloud.githubusercontent.com/assets/250509/26540134/c7776348-4447-11e7-9fd7-8490b85807d3.png">

The task is to:
* create a query that adds a route_offset field to siri_arrivals
* populates it with the correct values

Put the result query under the /postgres folder

**How to do it?**
* Assuming tasks siri_arrivals has a vehicle_location_point field (issue #30) and gtfs_shape_lines table exists (issue #29), this should be pretty easy to achieve using PostGIS ST_LineLocatePoint query ([see here](http://workshops.boundlessgeo.com/postgis-intro/linear_referencing.html)).

**What's would you need to implement this?**
* SQL, Some PostGIS (at least enough to run ST_LineLocatePoint). If you don't know any PostGIS these could help:
   * [Manual](http://www.postgis.net/docs/manual-2.3/)
   * [Tutorial](http://workshops.boundlessgeo.com/postgis-intro/)
* Some understanding of the siri_arrivals and gtfs_shape_lines table, though you really don't need to know much beyond the two geometry fields you're going to use.
* You can probably create the query using the [re:dash interface](http://data.obudget.org/). If you need a local dev copy of the database, see #32 
* Clone the repository and use pull requests to submit your code.

**Comment by daphshez** [comment]
Probably best to solve this entirely at the database level using PostGIS

We need to keep the shapes & points in Geometry fields and then use ST_LineLocatePoint 

See here:

http://workshops.boundlessgeo.com/postgis-intro/linear_referencing.html

**Comment by LiorDL** [comment]
-- Add route offset to siri_arrivals (see issue #26)
--Adding offset column 
ALTER TABLE siri_arrivals_filtered
ADD route_offset float8;

-- Populate data 
with join_result as (SELECT id, ST_LineLocatePoint(shape_line, siri_arrivals_filtered.vehicle_location_point) as line_locate_point_value
FROM siri_arrivals_filtered
JOIN gtfs_trips ON gtfs_trips.trip_id = siri_arrivals_filtered.trip_id_from_gtfs
JOIN gtfs_shape_lines ON gtfs_trips.shape_id = gtfs_shape_lines.shape_id)
 
update siri_arrivals_filtered 
set route_offset = join_result.line_locate_point_value
from join_result
where siri_arrivals_filtered.id = join_result.id

@daphshez , this issue can be also closed. Tanks
