### ISSUE TITLE
Document GTFS Stats configuration

### ISSUE THREAD

**Issue by OrBin** [hasadna/open-bus#266]
We should document GTFS Stats' [configuration file](https://github.com/hasadna/open-bus/blob/master/gtfs/gtfs_utils/gtfs_utils/config_example.json).

The type of configuration file may be changed if it is necessary for documenting better, but such a change must be discussed.

**Comment by TheFrok** [comment]
My plan for this issue:

- [ ] Document the fields in excel (name, required, description, default value).
- [ ] Insert the documentation to the project (maybe inside the JSON and clean in later, or in a different file).
- [ ] Create a test to check that all the config fields are documented.

**Comment by TheFrok** [comment]
@OrBin I think JSON SCHEME might be a good option for documenting the meaning of each field.
It is pretty simple and can be parsed to a doc using [sphinx](https://sphinx-jsonschema.readthedocs.io/en/latest/directive.html). what do you think?

**Comment by OrBin** [comment]
Sounds good. I think JSON schema is better than excel.
I didn't know this sphinx feature, nice!

**Comment by TheFrok** [comment]
For sure, the excel was just a draft of the documentation text. 
I wrote the json schema and I have two questions:

1. I haven't found any use for the `future_days_count` key in the configuration. Did I miss it or can I just delete it?
2. Can I set default values for the output file regexp, so it will be optional in the config?

**Comment by TheFrok** [comment]
[html.zip](https://github.com/hasadna/open-bus/files/3898363/html.zip)

Here are how the docs came out, if you want to see before I'm opening a pull request.

**Comment by OrBin** [comment]
About the `future_days_count` parameter - I'm not sure. I think it's a trace from older versions, but I don't really remember. @cjer, do you remember?

About the output file regexp - I wouldn't like to set a default value there, since it is related to how we name and store our files in S3, not to the GTFS Stats utility itself.

The docs look nice, but if you can find a way to prevent the horizontal scrolling that will be much better. Anyway, you can just open a PR, you don't have to post the output first.

**Comment by OrBin** [comment]
> My plan for this issue:
> 
> * [x]  Document the fields in excel (name, required, description, default value). [config doc.xlsx](https://github.com/hasadna/open-bus/files/3883744/config.doc.xlsx)
> * [x]  Insert the documentation to the project (maybe inside the JSON and clean in later, or in a different file).
> * [ ]  Create a test to check that all the config fields are documented.

Did you give up on the test?

**Comment by TheFrok** [comment]
> > My plan for this issue:
> > 
> > * [x]   Document the fields in excel (name, required, description, default value). [config doc.xlsx](https://github.com/hasadna/open-bus/files/3883744/config.doc.xlsx)
> > * [x]   Insert the documentation to the project (maybe inside the JSON and clean in later, or in a different file).
> > * [ ]   Create a test to check that all the config fields are documented.
> 
> Did you give up on the test?

Since the documentation is generated from the schema, and each field has to be added to the schema, I thought it would have much additional value.
I can test that every schema field is documened.

**Comment by OrBin** [comment]
Yes, that's what I was talking about. But from your explanation it seems
like it's unnecessary.

**Comment by OrBin** [comment]
Yes, that's what I was talking about. But from your explanation it seems
like it's unnecessary.
