### ISSUE TITLE
Create a database dump for dev environment + docker?

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#32]
Find an easy way for new volunteers to have write access to a copy of the database.

Preferably not the entire database but a subset (e.g. siri_arrivals from a single day + related gtfs data)

Can we put it into a docker container based [on this](https://github.com/hasadna/open-bus/blob/dfeaea67d8c4ed51bd0a4b0c30cffbac095ff81b/gtfs/local_db/README.md)? 

Alternatively we need good instructions on how to set up a database.

**Comment by MYank0** [comment]
created first version of tutorial [here](https://github.com/hasadna/open-bus/blob/master/doc/postgres_getting_started.md).
windows part still requires some improvements.

**Comment by daphshez** [comment]
@MYank0 should we close this issue at this point?

**Comment by MYank0** [comment]
@daphshez  sorry - didn't notice the comment. I'm closing.
