### ISSUE TITLE
Add SHAPE_DIST_RATIO field to gtfs_stop_times [easy] 

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#33]
gtfs_stop_times has a SHAPE_DIST_TRAVELED which gives the distance travelled by the bus from the route origin to the current stop. 

The task is to write a query that:
* Adds a shape_dist_ratio field to gtfs_stop_times table 
* Populate the field with the ratio between SHAPE_DIST_TRAVELED and the length of the route (values in 0-1 range)

Keep the query as an .sql file under /postgres 

You can get the length of the route by querying the SHAPE_DIST_TRAVELED of the last stop (highest STOP_SEQUENCE for the same TRIP_ID). 

**What  you will need to know?**
* SQL
* Understand the gtfs_stop_times table. Read about the [GTFS tables here](https://github.com/hasadna/open-bus/blob/master/doc/working_with_GTFS.md) and play with them using the [re:dash interface](http://data.obudget.org/).
* You can access the database and write the query using the re:dash database.
* Clone the repository and submit the query using a pull request.

**Comment by MYank0** [comment]
Issue was solved by @orifolger. Current GTFS is updated with this column and the sql query is saved under postgres. I added the query to the script [insert_gtfs.sql](https://github.com/hasadna/open-bus/blob/master/postgres/insert_gtfs.sql)
@daphshez can we close this issue?
