### ISSUE TITLE
Stride - REST API

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#340]
Should provide a REST API that will expose the Stride data in a structured way

See spec for more details: https://docs.google.com/document/d/1LcGlK0BfJ2C2jE0O0oDBjeidG8KfdNMpGH_bMskdrOc/edit?usp=sharing

**Implementation Notes**

* Should be in a new repository (`open-bus-stride-api`)
* I'm used to using [Flask](https://flask.palletsprojects.com/en/2.0.x/), but open to suggestions to use other frameworks
* Main goal for this issue is to get the basic operations working, and being open to add more API methods in the future

**Comment by AvivSela** [comment]
i would like to suggest to use[ FastAPI](https://fastapi.tiangolo.com/features/) instead. this framework become popular and provide out of the box open api documentation page that synced with the implementation of the API - so when we will change/add/remove fields - the documentation will update accordingly (less maintenance effort for us)

**Comment by OriHoch** [comment]
yes, FastAPI sounds good

**Comment by OriHoch** [comment]
I'll take this issue because it is blocking other tasks

**Comment by OriHoch** [comment]
done - 
https://open-bus-stride-api.hasadna.org.il/docs
https://github.com/hasadna/open-bus-stride-api

**Comment by cjer** [comment]
Looks awesome! Oh how I love fastapi :)
