### ISSUE TITLE
stride gtfs etl: should have runnable tasks that can be used via Airflow

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#343]
I made some changes to integrate the [open-bus-gtfs-etl](https://github.com/hasadna/open-bus-gtfs-etl) with the rest of the stride project and with the Airflow server

Currently, looks like the gtfs-etl has all the required components but we need to package it as runnable tasks which can be scheduled daily on Airflow

requirements:

* Have a task or series of tasks which can be run without any parameters daily to update the gtfs data in db
  * I think there should be 2 tasks:
    * download the daily gtfs data and store in a directory structure (e.g. gtfs_data/YEAR/MONTH/DAY)
    * process the daily gtfs data and update in DB (uses the last day by default, but can accept a parameter of a specific day)
* additional requirements to better support the integration and working in the airflow and docker system:
  * all configurations should be as environment variables, preferaly very minimal configuraiton is needed, I think just the directory name where to store the data
  * output/input directories should not be passed as parameters, but use a single env var with a directory name, and use standard names of subdirectories in that directory (this supports using with a docker volume)
  * all commands should be implemented as api methods, with a user interface in the CLI method

example from another project:

* required environment variables are specified in the README (I don't think there are any of those in gtfs-etl): https://github.com/hasadna/open-bus-siri-requester#required-environment-variables
* config file contains all the configurations from environment variables with default values for development where applicable: https://github.com/hasadna/open-bus-siri-requester/blob/main/open_bus_siri_requester/config.py
* file paths are all based on a single rootpath from the configuration: https://github.com/hasadna/open-bus-siri-requester/blob/main/open_bus_siri_requester/storage.py#L82

**Comment by AvivSela** [comment]
- we agreed on 3 tasks:

    1. Download the daily gtfs data and store in a directory structure (e.g. gtfs_data/YEAR/MONTH/DAY)
    2. Analyzing  the daily gtfs data and store in a directory structure (e.g. stat_data/YEAR/MONTH/DAY)
    3. Load analyzed data into database.

- environment variable: "**GTFS_ETL_ROOT_ARCHIVES_FOLDER**" will be used to get root folder for the gtfs and stat archives.

**Comment by OriHoch** [comment]
tasks 2 and 3 should accpet a parameter which specifies the year/month/day to work on (by default - last year/month/day)

**Comment by AvivSela** [comment]
i added the 3 tasks. Documentation about them added to the Readme file:
https://github.com/hasadna/open-bus-gtfs-etl#supported-operations-and-configurations

**Comment by OriHoch** [comment]
@AvivSela completed the integration with airflow

dag is now running daily

data is available at https://open-bus-gtfs-data.hasadna.org.il/
