### ISSUE TITLE
check why there is a duplicate stop

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#348]
following query returns 2 stop items for the same stop code and validity date (gtfs=true)

this should not happen, need to see why it happens

https://open-bus-stride-api.hasadna.org.il/stops/list?valid_for_date=2021-10-16&code=32891

**Comment by AvivSela** [comment]
do you have more details about the scenario?

**Comment by OriHoch** [comment]
no, I just see this in the DB, the rows are with gtfs=true so they are generated from the gtfs etl process

**Comment by AvivSela** [comment]
https://github.com/hasadna/open-bus-gtfs-etl/pull/12

**Comment by AvivSela** [comment]
re-assign this task to Ori, for a review.

**Comment by OriHoch** [comment]
fixed in https://github.com/hasadna/open-bus-gtfs-etl/pull/12 and https://github.com/hasadna/open-bus-gtfs-etl/pull/15
