### ISSUE TITLE
check duplicate ride.journey_ref

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#349]
### reproduction steps
* https://open-bus-stride-api.hasadna.org.il/rides/list?journey_ref_prefix=24564655_161021&is_from_gtfs=true&scheduled_start_time_from=2021-10-15T00%3A00%3A00

#### expected
* A single ride per journey_ref

#### actual
* 2 rides
* the second ride has journey ref suffix `_161021` - but scheduled start time date of `2021-10-17`

**Comment by AvivSela** [comment]
@OriHoch, the link returns error traceback, could you provide more details?

**Comment by OriHoch** [comment]
assigning to me to check it

**Comment by OriHoch** [comment]
fixed in hasadna/open-bus-gtfs-etl#12 and hasadna/open-bus-gtfs-etl#15
