### ISSUE TITLE
Create a script to archive GTFS nightly

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#35]
We currently rely on the GTFS archive of Open Train. 

Unfortunately they can delete files from there without consulting us (it's much less important to them currently than it is to us). 

We need to write a script that downloads the files ([Open train script](https://github.com/hasadna/OpenTrain/blob/25ff81df668a9eba1c4369f9a789e34c60b44096/webserver/opentrain/gtfs/utils.py) is a good starting point) and deploy it to run nightly.

**Comment by florpor** [comment]
added script and a daily cron job that runs in obus-dev server.
cron script lives in /etc/cron.daily

@daphshez can you close please?

**Comment by daphshez** [comment]
I think the script has some problems when running as cron job. Anyway I can't see the files accumulating anywhere. I disabled the cron job for now so.

It needs to:

- [ ] Receive the root directory under which the files will be kept as a script parameter. 
- [ ] Log to somewhere where the logs remain visible. Probably easiest to redirect stdout and stderr to a tmp file (>& the output of the script in the crontab)



cc @MYank0 as well.

**Comment by efratoio** [comment]
Hi, I added a job to cron.daily  - gtfs_sh
the script is under gtfs/retriever/gtfs_retrievr_sh.sh
the log file is /var/log/gtfs_archive.log
and the files are kept under /srv/gtfs_archive/date.zip
if you have disabled cron.daily it will not run.

**Comment by daphshez** [comment]
thanks @efratoio 
I'll have another look, but anyway hopefully very soon we will want to upload the files to s3 so the script will have to be changed.

**Comment by efratoio** [comment]
Sounds very good.

**Comment by daphshez** [comment]
superseded by #46
