### ISSUE TITLE
add retry mechnism to stride-gtfs-etl download step

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#350]
## reproduction steps
* Run the download step but have a failure due transient networking problems
* for example: https://open-bus-airflow.hasadna.org.il/log?dag_id=gtfs-etl&task_id=download&execution_date=2021-10-18T00%3A00%3A00%2B00%3A00

### expected
* should retry the download a configurable number of times with configurable delay between each try

### actual
* fails

**Comment by OriHoch** [comment]
@AvivSela this issue is done?

**Comment by AvivSela** [comment]
yes
