### ISSUE TITLE
Swagger link to API does not work

### ISSUE THREAD

**Issue by evyatark** [hasadna/open-bus#353]
the link https://open-bus-stride-api.hasadna.org.il/docs returns
503 Service Temporarily Unavailable
(for at least 5 days now)

**Comment by OriHoch** [comment]
thanks, I made some substantial changes last week to the DB structure which broke the API, I will try to fix it today/tomorrow

**Comment by OriHoch** [comment]
fixed https://open-bus-stride-api.hasadna.org.il/docs
