### ISSUE TITLE
Multiple routes created for line refs with same data each day

### ISSUE THREAD

**Issue by AdlerShay** [hasadna/open-bus#354]
{
    "id": 588220,
    "min_date": "2021-11-06",
    "max_date": "2021-11-06",
    "line_ref": 11692,
    "operator_ref": 16,
    "siri_published_line_name": null,
    "gtfs_route_short_name": "1",
    "gtfs_route_long_name": "מרכזית הקריות-קרית ים<->ת. מרכזית חוף הכרמל/רציף לילה ושבת-חיפה-27",
    "gtfs_route_mkt": "83001",
    "gtfs_route_direction": "2",
    "gtfs_route_alternative": "7",
    "gtfs_agency_name": "סופרבוס",
    "gtfs_route_type": "3",
    "is_from_gtfs": true
  },
  {
    "id": 602044,
    "min_date": "2021-11-07",
    "max_date": "2021-11-07",
    "line_ref": 11692,
    "operator_ref": 16,
    "siri_published_line_name": null,
    "gtfs_route_short_name": "1",
    "gtfs_route_long_name": "מרכזית הקריות-קרית ים<->ת. מרכזית חוף הכרמל/רציף לילה ושבת-חיפה-27",
    "gtfs_route_mkt": "83001",
    "gtfs_route_direction": "2",
    "gtfs_route_alternative": "7",
    "gtfs_agency_name": "סופרבוס",
    "gtfs_route_type": "3",
    "is_from_gtfs": true
  }

**Comment by OriHoch** [comment]
thanks!

**Comment by AvivSela** [comment]
this issue should be resolved by hasadna/open-bus-gtfs-etl#12
please verify.

**Comment by OriHoch** [comment]
fixed in hasadna/open-bus-gtfs-etl#12 and hasadna/open-bus-gtfs-etl#15
