### ISSUE TITLE
Error when using Python API

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#356]
I've copied the cells from the [example notebook](https://hub.gke2.mybinder.org/user/hasadna-open-bus-stride-client-it1mquxw/doc/tree/notebooks/Load%20route%20rides%20to%20dataframe.ipynbl) but I am getting this error when trying to query the database - 
![image](https://user-images.githubusercontent.com/42667498/145251317-aab64a27-9fed-4fc9-880e-8d99d9b70528.png)

Do you know what could I do to make it work?

(and minor note - "df = PD.DataFrame" should be changed to "df = pandas.DataFrame" to be aligned with the import cell)

**Comment by OriHoch** [comment]
the bug is not reproduced for me, looks like it gets some invalid response from the API, I will create an issue to have relevant details in the error message

regarding the import pands - it's standard usage to do `import pandas as PD` and then refer to pandas as `PD` - I believe pandas documentation itself uses it this way.

**Comment by OriHoch** [comment]
I added more error details, please try again with latest client and post the error you get here

if you are running locally upgrade using `pip install --upgrade open-bus-stride-client`

**Comment by EyalBerger** [comment]
Great! I've upgraded it and now it's works, thank you.

about the pandas point - I meant the code in the example isn't aligned - we "import pandas" (without as pd) but consume PD later on in the code. It isn't so important, just suggesting to align it.

**Comment by OriHoch** [comment]
the notebook does `import pandas as PD` - https://github.com/hasadna/open-bus-stride-client/blob/main/notebooks/Load%20route%20rides%20to%20dataframe.ipynb

**Comment by EyalBerger** [comment]
great. Closing this issue
