### ISSUE TITLE
Build incremental GTFS database [epic, needs breaking down into tasks]

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#36]
The GTFS is published by MoT nightly. Each file contains data for the next 60 days, but changes to planning can occur: the GTFS files from the 1/1 and 2/1 may disagree on the trips planned for the 2/1. The data published on the 2/1 should be considered more accurate because it is more up to date.

We need a script that:
* For every day, loads the data from the GTFS file of that day (or the most recent file we have) to a Postgres DB. 
* Can add one GTFS file to an existing database. 
* Can work on an archive of GTFS files and load data incrementally from them.

An outline for the incremental db schema and logic for implementing the task [can be found here](https://docs.google.com/document/d/181MldFNq4YwCDbdv2XdSit_BJmRRVeJR0jzi4LDmgbc/edit?usp=sharing).

An archive of GTFS files to test with is kept by [Open Train](http://gtfs.otrain.org/static/archive/).

**Comment by daphshez** [comment]
![download](https://user-images.githubusercontent.com/250509/27038577-55335a3e-4f83-11e7-82e8-5a512739836f.png)

**Comment by AvivSela** [comment]
Alternative schema: 
![obus_schema](https://user-images.githubusercontent.com/10119579/34628184-28c75554-f26c-11e7-9054-cfcc2f77f763.png)
