### ISSUE TITLE
remove min_date/max_date fields and have a single date field

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#360]
following discussions on #359 and PR hasadna/open-bus-gtfs-etl#12 it seems there are too many problems and implementation complexity with the requirement to have min_date/max_date fields on the gtfs data

To reduce complexity we will remove this requirement for now

### To Do:
* change all gtfs DB tables - remove min_date/max_date fields and add a single date field
* change gtfs-etl process to create a single record per date

**Comment by OriHoch** [comment]
assigning to @AvivSela and setting to In progress because it should be done as part of the currently in progress task to remove duplicate stops

**Comment by OriHoch** [comment]
@AvivSela I will implement the DB changes

**Comment by AvivSela** [comment]
so, are we going to duplicate the data for each date even it won't be modified?
in case I uploaded stop, and tomorrow the stop is the same, should we upload it again?

**Comment by OriHoch** [comment]
yes, each record will be valid for a single date specified in the `date` field

**Comment by OriHoch** [comment]
I will try to have the DB changes ready today / tomorrow

**Comment by OriHoch** [comment]
DB changes are done and merged, I renamed all the tables to have gtfs prefix to make it clear these tables are only used for gtfs data - https://github.com/hasadna/open-bus-stride-db/pull/7

**Comment by AvivSela** [comment]
the changes in the GTFS ETL about the schema change are included in the pr (hasadna/open-bus-gtfs-etl#12) that was opened for #348
