### ISSUE TITLE
siri_rides/list functions' results seems to be not aligned with the parameters

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#361]
Hi,
Maybe I am missing something, but isn't it weird there are multiple "route_id"s at the output, while we requested for a single "route_id" on the parameters section? it's same when we query with "get"  

![image](https://user-images.githubusercontent.com/42667498/146692823-4ed4bdb9-3f64-4e03-8b21-78263d6c14bc.png)

**Comment by OriHoch** [comment]
[fixed](https://github.com/hasadna/open-bus-stride-client/commit/8186fe2ae7629fd45c4fe9a405ee1735e7d3e36e)

the argument name was wrong - it should have been `siri_route_ids` instead of `route_ids`

I opened an issue to have the API raise an exception in case of unknown argument - #362
