### ISSUE TITLE
Adding optional parameters function

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#379]
I think it would be very useful for users to have a function which returns the optional parameters of a list (siri_routes, gtfs_routs, etc.).

see example below - I am trying to use "date" parameter but I am getting wrong results. I am not sure why, but if I could easily see the optional parameters list, I could check if "date" is included there.

![image](https://user-images.githubusercontent.com/42667498/155898737-bd31003b-1e49-4b25-a2b5-6f5dd9999057.png)

**Comment by OriHoch** [comment]
all the api methods and parametes are documented in the api documentation: https://open-bus-stride-api.hasadna.org.il/docs#/gtfs/list__gtfs_routes_list_get

**Comment by EyalBerger** [comment]
Great, thanks!
Does this doc is getting updated automatically when adding new filters or we should pay attention to update it?

**Comment by OriHoch** [comment]
It's updated automatically

**Comment by EyalBerger** [comment]
Great. Closing this issue
