### ISSUE TITLE
Limit parameter doesn't work for some queries 

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#380]
It seems the "limit" parameter isn't working for some tables as siri_rides and siri_routes, and there is a default limit of 1000 results which can't be changed by the user. Could we add the an option to change the limit value?

![image](https://user-images.githubusercontent.com/42667498/155898999-74f7ec84-7a51-4ffd-9268-a88de93d9eb2.png)

**Comment by OriHoch** [comment]
For list operations you should use the `list` method which seamlessly iterates over items and does accept a `limit` parameter.

https://github.com/hasadna/open-bus-stride-client#usage

The `get` method passes all params as-is to the underlying api, so you can add the limit argument as part of the params like this:

```
stride.get(`/siri_rides/list`, {
  'siri_route_ids': '1926',
  'limit': 10000
})
```

Also, the underlying API does not allow a limit of more then 1000 items, the client `list` method seamlessly handles it and does multiple calls which allows to have unlimited items.

**Comment by EyalBerger** [comment]
Thanks! as you said - I've moved the 'limit' parameter and now it works properly. Closing this issue
