### ISSUE TITLE
siri_vehicle_locations doesn't includes siri_ride__id

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#381]
It seems the siri_ride__id is missing from the output

![image](https://user-images.githubusercontent.com/42667498/155899238-ad08b9e2-7164-4027-ab88-d9d4878ec860.png)

**Comment by EyalBerger** [comment]
Thanks! does the changes have been merged and we can close this issue?

**Comment by OriHoch** [comment]
changes were not merged yet

**Comment by OriHoch** [comment]
the changes were merged and deployed
