### ISSUE TITLE
siri_vehicle_locations "limit" parameter doesn't limits properly 

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#382]
Changing the limit value to 100 still retrieves 1000 results. 

![image](https://user-images.githubusercontent.com/42667498/155899738-b21741fe-6e10-44b4-b087-c0479c0ee7ee.png)

**Comment by OriHoch** [comment]
@EyalBerger fixed in latest open-bus-stride-client verion 0.0.5, make sure you use latest version, e.g. `pip install --upgrade open-bus-stride-client`
