### ISSUE TITLE
Wrong data type on parameter retrieves wrong results instead of raising an error

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#384]
Hi, I think this should also raise an error as the data type is wrong (time instead of date) , but it retrieves wrong results:

![image](https://user-images.githubusercontent.com/42667498/156901909-a153d7e4-5c55-4854-82b4-a50fbec43411.png)

**Comment by OriHoch** [comment]
@EyalBerger why do you think it's a wrong datatype? why do you think it's the wrong results? please elaborate

**Comment by OriHoch** [comment]
also, would be more helpful if you could paste the text itself and not an image, that way we could run this code

**Comment by EyalBerger** [comment]
@OriHoch - sorry. my mistake, I've confused between two date columns.
closing this issue as no action is required
