### ISSUE TITLE
Can't access siri br file 

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#385]
![image](https://user-images.githubusercontent.com/42667498/156901940-a58f274b-2313-48b4-9d4b-914ca360ed18.png)

any idea what should I do?

I can access this specific link that you've shared with me: https://openbus-stride-public.s3.eu-west-1.amazonaws.com/stride-siri-requester/2022/03/01/07/00.br

**Comment by OriHoch** [comment]
you need to replace the date/time placeholders:

* `yyyy` - year (four numbers)
* `mm` - month (two numbers)
* `dd` - day (two numbers)
* `HH` - hour (two numbers)
* `MM` - minutes (two numbers)

**Comment by EyalBerger** [comment]
it works, thanks you!
