### ISSUE TITLE
API call gets an error: "QueuePool limit of size 5 overflow 10 reached"

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#387]
Hi, I am not able to access the API for the last few hours (Python or Web), and getting the above error.

Request URL: `https://open-bus-stride-api.hasadna.org.il/siri_vehicle_locations/list?siri_routes__line_ref=12406`

Error message: `QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)`

From the link I understand this could be because the connection pool is full, or because completed connections are not getting closed correctly. 

any suggestions what to do?

**Comment by OriHoch** [comment]
Looks like a lot of idle transactions in the DB from the api
 
[postgres_pg_catalog_pg_stat_activity.xlsx](https://github.com/hasadna/open-bus/files/8229247/postgres_pg_catalog_pg_stat_activity.xlsx)

**Comment by OriHoch** [comment]
@EyalBerger I restarted the API, so requests are working now, but it's possible that this will occur again after too many requests are made, I will try to fix the root cause

**Comment by OriHoch** [comment]
fixed + deployed

**Comment by EyalBerger** [comment]
Great, thanks @OriHoch!
