### ISSUE TITLE
permission to push to open-bus-stride-client

### ISSUE THREAD

**Issue by EyalBerger** [hasadna/open-bus#392]
Hi, I don't have permission to push to open-bus-stride-client:

`git push --set-upstream origin update_demo_notebook`

```
remote: Permission to hasadna/open-bus-stride-client.git denied to EyalBerger.
fatal: unable to access 'https://github.com/hasadna/open-bus-stride-client/': The requested URL returned error: 403
```

Could you please give me a permission?

**Comment by OriHoch** [comment]
I prefer to use the standard open source workflow of forking and then opening PRs from the fork, that way no permissions are needed and anyone can open a PR and suggest changes

This workflow is described here: https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by EyalBerger** [comment]
Sure. I did it now in this way. thanks!
