### ISSUE TITLE
get number of results for each api call

### ISSUE THREAD

**Issue by idshklein** [hasadna/open-bus#395]
the api limits call to a hundred results in each call. 
knowing the number of results can help scrape the results using offset.
I do not know whether this has the potential of dramatically increasing computation costs, but it can give a perception regarding the population of events in question. 

example of usage:
Request url:
https://open-bus-stride-api.hasadna.org.il/siri_vehicle_locations/count?param1=x&param2=y
response:
`{"param1":x,"param2":y,"count":150}`

**Comment by OriHoch** [comment]
done, you can add `&get_count=true` to any list method to get the total number of results for given query
