### ISSUE TITLE
[Transferred from GitLab] Implement a function to extract bus stops for a given route

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#4]
Need to implement a function which gets a bus route + departure stop and returns a list of stops for that route.

Originally posted by @johananl

**Comment by johananl** [comment]
Should this function query the DB or CSV files?
Also, do we have a running DB with sample data already?

**Comment by daphshez** [comment]
see [this issue](https://github.com/hasadna/open-bus/issues/5) for the status of the GTFS DB. I believe the short version is that the database is ready but the load script still needs updating. 

Whether DB or CSV should be used depend on what you need this for. 

It's not a problem to add write a function that finds it using the [GTFS class](https://github.com/hasadna/open-bus/blob/master/gtfs/parser/gtfs_reader.py), and especially if [route stories](https://github.com/hasadna/open-bus/blob/master/gtfs/parser/route_stories.py) were generated.
But reading the entire GTFS to query a single route will be quite slow. 

So maybe you better explain the use case...

**Comment by daphshez** [comment]
I implemented an interactive script that exports the stops for a line: 

https://github.com/hasadna/open-bus/blob/master/gtfs/parser/line_stops_finder.py

It's interactive because it gives you all the routes that match a given line number, and asks you to choose which one you want. 

It works with the GTFS file rather than DB. It also requires route stories. 

I think that covers this task for now (maybe we would want to re-implement in the future using DB), so I am closing it.
