### ISSUE TITLE
stride-api feature request: add parameter to siri_ride to enable querying gtfs_ride_id

### ISSUE THREAD

**Issue by idshklein** [hasadna/open-bus#405]
according to [this schema](https://github.com/hasadna/open-bus-stride-db/blob/main/dbschema.png), it is possible to join siri_ride and gtfs_ride through shared keys. however, it seems that querying siri_ride according to gtfs_ride is not possible.
in order understand the need for this feature., let's assume you have a list of routes You queried from  GTFS according to Location., for example. You want to take the MK T and query the rides That occurred. In siri. Currently this is Impossible.

**Comment by OriHoch** [comment]
done, added all related gtfs_ride / route filters to siri_ride/list api method
