### ISSUE TITLE
Data Analysis - Create Reports For 480,19,947

### ISSUE THREAD

**Issue by MYank0** [hasadna/open-bus#41]
Create reports with the data we have regarding lines: 480, 19, 947.
The reports should include the following analysis:

- [ ] Per Date - how many trips were planned (by GTFS) how many we actually received GPS coordinates (from SIRI). for example: 99 trips were planned but we saw only 91 in SIRI.
- [ ] Which buses left their first stop late?
- [ ] How late are the buses on other stops? (not just the first)
- [ ] How long does each trip takes from start to end?

If you have other ideas you are more than welcome to add them! 🥇

**Comment by shovalsa** [comment]
current gtfs is from July. Lines to be analyzed are 572, 5
