### ISSUE TITLE
Optimize siri_arrivals data

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#42]
siri_arrivals has a huge (and hopefully growing) number of records, so we need to be more careful about the size of each record. 

We need to make some changes to the current table as well as to the code that creates the table:

- [x] Change trip_id to varchar(20)  
- [x] Change vehicle_location_lat and vehicle_location_lon to varchar(8)  (5 digit decimal precision is enough)
- [x] Drop columns confidence_level, arrival_boarding_activity
- [x] Review other fields and see if the type can be changes or the field can be dropped completely.

**Comment by MYank0** [comment]
1. can we drop the following fields?
'request_stop', 'destination_display',  'actual_arrival_time',  'arrival_status',  'arrival_platform_name','actual_departure_time', 'aimed_departure_time', 'stop_visit_note',  - based on this [doc](https://github.com/hasadna/open-bus/blob/master/doc/db_tables.md) + queries they are are always empty/ not relevant.

2. I want to erase records we don't need based on this query: 
`select * from siri_arrivals where recorded_at_time::time < Origin_aimed_departure_time::time and Vehicle_location_lat in ('');`
what do you think? It will erase all records without gps coordinates but only if we got the response before the departure time from first stop.
currently this query counts 14 million records out of 31 million.

3. We dropped the column Vehicle_location_point.

**Comment by daphshez** [comment]
1 - seems good to me. 
2 - It makes sense, but I would suggest not delete records until we are done with this research stage, and we are absolutely sure what's useful for us.
3 - Wouldn't it make more sense to drop the lat & long as string and keep the geometry field?

**Comment by MYank0** [comment]
made pull request:
1. Remove unnecessary fields
2. Change vehicle_location_lat and vehicle_location_lon to varchar(8) - make changes in code to round the result.

After pull request is accepted will run:

UPDATE siri_arrivals
SET vehicle_location_lat = NULL
AND vehicle_location_lon = NULL
WHERE vehicle_location_lat = '';

ALTER TABLE siri_arrivals
ALTER COLUMN vehicle_location_lat TYPE double precision USING round(vehicle_location_lat::numeric,5);
ALTER TABLE siri_arrivals
ALTER COLUMN vehicle_location_lon TYPE double precision USING round(vehicle_location_lon::numeric,5);

and drop all unnecessary columns

**Comment by daphshez** [comment]
@MYank0 , if that pull request was for me to review - it looks alright to me. I am not that fresh with the code that I feel I'm particularly equipped to review it though... Suggest you merge it if it seems to be working!

**Comment by MYank0** [comment]
done.

**Comment by daphshez** [comment]
is there anything else to do on this issue or shall we close it?

**Comment by MYank0** [comment]
Finished all 4 task - closing :)
