### ISSUE TITLE
Update nightly GTFS script to upload to S3

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#46]

**Comment by MYank0** [comment]
Script updated and installed via crontab since cron.daily is not working.
Tried figuring out why cron.daily doesn't work but got stuck. We don't have anacron installed, have it ever worked?
using crontab last night it downloaded the gtfs and uploaded to bucket so it seems to be working.

**Comment by MYank0** [comment]
installed and working on obus user
