### ISSUE TITLE
Simplify shapes

### ISSUE THREAD

**Issue by daphshez** [hasadna/open-bus#6]
GTFS shape.txt contains a list of coordinates for transport routes.

These lists aren't efficient for drawing the shape on the map. They are over-specified (have too many points). See for example [this map of line 28א in Jerusalem](https://www.google.com/fusiontables/DataSource?docid=1GIi593kSHEwaJ878DfcmnNEZiluDzBVU8dubcK5A) (picked at random).

This is a problem if want to to presents the lines on a map. 

[Ramer–Douglas–Peucker](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm)  is a pretty straight forward algorithm to simplify polylines . There's a [Python implementation here](https://github.com/fhirschmann/rdp/issues/5).

What needs doing is:

1. Add a new database table simplified_shape with the same table definition as shapes
2. Read all shapes from the shapes table that are missing from simplified_shape
3. Run RDP
4. Write to simplified_shapes

Since the data is still not in the DB, an intermediate task would be:
1. Read the shapes using https://github.com/hasadna/open-bus/blob/master/gtfs/parser/gtfs_reader.py
2. Run RDP
3. Dump results to a CSV file in the same format as the original shape.txt (shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence)

**Help wanted:**
This is an independent task that doesn't really require coordination with the rest of the project and is perfect for a new volunteer. I would estimate it 1-3 work days, depending on experience.

**Comment by daphshez** [comment]
@shalevguy will be working on this task using the simplyshape branch.

**Comment by MYank0** [comment]
I will be Working on this task
