### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#64]
I feel the our project could use some order-making, and a boost to its accessibility to newcomers and sparsely-contributing members. My first offer in this direction is to come up with a good `CONTRIBUTING.md` file that will be suggested to every newcomer to read, and linked to on every issue, pull-request and commit creation. 

### Contents
Besides pointing to the basic resources for getting started, should include at least the following contribution type guidelines - 
1. Documentation
1. New features
1.  Bug reports
1. Use case / Analysis
#### For code contributions
1. Small - pull request
1. Large - disscussion issue -> design-> pull-request
1. How to submit a proper Pull Request
1. Test guidelines

**Comment by zvigrauer** [comment]
Good, it's about time...
