### ISSUE TITLE
Write a SQL query for trips that did not departed

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#68]
The query should compare the real time information of the first station with the GTFS time and return the trips that are 8 minute late or more.

**Definition Of Done**
- Save the SQL query in the new re:dash. [https://app.redash.io/hasadna/]

**Comment by AvivSela** [comment]
@yakik 
re:dash is working now: https://app.redash.io/hasadna

**Comment by yakik** [comment]
Query is ready, however there is some time difference (like timezone) between GTFS and Siri. We need to check this.
