### ISSUE TITLE
Find residential areas with no stops

### ISSUE THREAD

**Issue by cjer** [hasadna/open-bus#78]
- Retrieve polygons for countrywide residential areas, preferably with number of residents - OpenStreetMap / Google / CBS
- Use GTFS stops to color parts of residential areas (over a certain threshold of residents) which are far from a stop (e.g. over 1KM from nearest stop which at least one trip stops at to and from)

**Comment by zvigrauer** [comment]
We had some geographers from Beer Sheva and TAU who surely have access to
this required data.

Also, this sound like a perfect job for a GIS system such as QGIS or
ArcGIS, which again, these individuals could furnish you with access to.

It would be interesting to form a GIS model that can reach the gfts data
(you can run python from within the GIS system), parses it and does the
geoprocessing you require.

Z.
