### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by efratoio** [hasadna/open-bus#8]
Hi,
I am talking with Yehuda and he is preparing a server for us.
We must note that the prev server was diagnosed with a dangerous virus and was put to sleep by Yehuda.
So - no more viruses!
We are getting a ubuntu 16 server with nginx and postgres. 
What are the first things we would like to do with it, other then creating the db?

**Comment by daphshez** [comment]
I think the first script would be a script that loads the GTFS nightly to the DB,
and of course a script that runs SIRI queries and loads the results to the DB (once the IP problem is solved).

I think it would be useful to install Apache as well. For example, we might want to run a webapp showing stops and routes on the map, like I started doing in [stops_service](https://github.com/hasadna/open-bus/blob/kavrazif/gtfs/web/stops_service.py). Whatever framework we use for that we will need Apache.

**Comment by efratoio** [comment]
Nginx can be used for our webaps instead of Apache

**Comment by daphshez** [comment]
I think the server is configured as requested now, so I am closing the issue.
